# Generated by Django 4.2 on 2023-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color_theme',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white')], default=1, max_length=50, verbose_name='Color theme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('kz', 'kz'), ('ru', 'ru'), ('en', 'en')], default=1, max_length=5, verbose_name='Language'),
            preserve_default=False,
        ),
    ]
