# Generated by Django 4.1 on 2023-04-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_days', models.IntegerField(verbose_name='Amount of days')),
                ('done_date', models.DateField(verbose_name='Done date')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='habit.habit', verbose_name='Habit')),
            ],
        ),
    ]
